base_url = "https://lucdev.net"
compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
# Put all your custom variables here
