base_url = "https://lucdev.net"
compile_sass = true
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
# Put all your custom variables here
