version: "3"
services:
  server:
    build: .
    container_name: lucsite
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:8080:8080"

