name: Build and deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-22.04
    steps:
    - name: Test connectivity
      run: curl -v https://git.lucdev.net
    - name: Checkout code
      uses: actions/checkout@v4
      env:
        GIT_TRACE: 1
        GIT_CURL_VERBOSE: 1
    - name: Install pnpm
      uses: https://github.com/pnpm/action-setup@v4
      with:
        version: 9
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Lint
      run: pnpm run lint
    - name: Build project
      run: pnpm run build
    - name: Deploy
      run: pnpm run deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
