name: mypli deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Pull
      run: |
        curl --fail --request GET --url ${{ secrets.MYPLI_URL }}/luxlibre/lucsite/pull -H 'KEY: ${{ secrets.MYPLI_KEY }}'
    - name: Deploy
      run: |
        curl --fail --request GET --url ${{ secrets.MYPLI_URL }}/luxlibre/lucsite/deploy -H 'KEY: ${{ secrets.MYPLI_KEY }}'
